### PR TITLE
small updates for outcomes, docs, and roadmap

### PR DESCRIPTION
**Pull request by zackbradys**
*Issue: #62*

* Added updates for Workshop Outcomes and Documentation for Rancher Monitoring
* Updated Roadmap to account for recent changes and merges in the Workshop
* Cleaned up READMEs to match formatting and styling updates
* Updated a few content pages to match formatting updates

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by zackbradys** [comment]
Which VS Code styling and formatting extension have you been using @evdevr? Tried to undo any automatic changes from my VS Code, but happy to run it before we merge

**Comment by evdevr** [comment]
@zackbradys VS Code settings:
- Default Formattter: Prettier - Code formatter (installed extension Prettier from prettier.io)
- Editor: Format on Save enabled
- Prettier: Single Quotes checked (instead of double quotes)

**Comment by zackbradys** [comment]
Prettier formatting completed. LGTM from me! @evdevr

**Comment by zackbradys** [comment]
Reminder to review and/or approve! @evdevr @marshkkm

**Review by evdevr — APPROVED** [review]
lgtm, thanks zack

**Pull request merged**
